CREATE TABLE TBL_MEMBER 
(
    USERID VARCHAR2(50) NOT NULL PRIMARY KEY,
    USERPW VARCHAR2(100) NOT NULL,
    USERNAME VARCHAR2(100) NOT NULL,
    REGDATE DATE DEFAULT SYSDATE,
    UPDATEDATE DATE DEFAULT SYSDATE,
    ENABLED CHAR(1) DEFAULT '1'
);

CREATE TABLE TBL_MEMBER_AUTH
(
    USERID VARCHAR2(50) NOT NULL,
    AUTH VARCHAR2(50) NOT NULL,
    CONSTRAINT FK_MEMBER_AUTH FOREIGN KEY (USERID) REFERENCES TBL_MEMBER (USERID)
);

CREATE TABLE PERSISTENT_LOGINS 
(
	USERNAME VARCHAR2(64) NOT NULL,
	SERIES VARCHAR2(64) PRIMARY KEY,
	TOKEN VARCHAR2(64) NOT NULL,
	LAST_USED DATE NOT NULL
);